#page title
page_title                                : Looniewise                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ca                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Looniewise                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Looniewise is a smart shopping assistant that helps you save money on groceries by finding the best prices across multiple stores. Simply enter your grocery list, and Looniewise will create an optimized trip plan, directing you to the stores with the lowest prices for each item. Available in Saskatoon, with more cities coming soon. Download the app to start saving today!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.
show_links                                : false
show_coming_soon                          : true
app_launched                              : false



# # Information About Yourself
# your_name                                 : Emil Baehr                                
# your_link                                 : https://emilbaehr.com                     
# your_city                                 : Copenhagen                                
# email_address                             : emil.baehr@gmail.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
# github_username                           : emilbaehr
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Price Comparison Across Multiple Stores
    description                           : Automatically compare prices for each item on your grocery list across various stores in your area, ensuring you get the best deals.
    fontawesome_icon_name                 : shopping-cart
    
  - title                                 : Optimized Shopping Route
    description                           : Generate a custom trip plan that shows you the most efficient route to visit the stores with the lowest prices, saving both time and money.
    fontawesome_icon_name                 : route

  - title                                 : Smart Grocery List
    description                           : Create and manage your grocery list within the app, and Looniewise will automatically find the best deals for each item on your list.
    fontawesome_icon_name                 : list

  # - title                                 : Automatic Icon and Metadata
    # description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    # fontawesome_icon_name                 : sync

  # - title                                 : Easy to Tweak
  #   description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
